FROM python:3.11.0-slim

WORKDIR /usr/src/app
COPY . .

RUN apt update && \
    pip install -U pip && \
    pip install -r requirements.txt

EXPOSE 80

CMD ["python", "manage.py", "runserver", "0.0.0.0:80"]
